filter {
  if [user.name] in ["logstash_internal", "logstash_alerts_writer", "kibana_system", "_system"] {
    drop {}
  }

  if [event.action] != "access_granted" {
    drop {}
  }

  if [request.name] not in ["DeleteRequest", "DeleteIndexRequest", "BulkRequest", "UpdateRequest"] {
    drop {}
  }

  if ![indices] or [indices][0] !~ /^security-audit-/ {
    drop {}
  }

  mutate {
    add_field => {
      "alert_type"        => "LOG_TAMPERING"
      "alert_severity"    => "CRITICAL"
      "alert_description" => "Modification ou suppression detectee sur un index de logs applicatifs"
    }
    remove_field => ["@version", "host"]
  }
}
