input {
  http {
    port => 5044
    codec => json
    ssl_enabled => true
    ssl_certificate => "/usr/share/logstash/config/certs/elk.crt"
    ssl_key => "/usr/share/logstash/config/certs/elk.key"
  }
}