filter {
  if ![audit_chain][sequence] or ![audit_chain][hash] {
    mutate { add_tag => ["alerte_integrite_manquante"] }
  }

  mutate {
    add_field => {
      "raw_string_for_hash" => "%{[@timestamp]}%{[log][level]}%{[service][name]}%{[event][action]}%{[user][id]}%{[user][roles][0]}%{[source][ip]}%{[patient][id]}%{[audit_chain][sequence]}%{[audit_chain][previous_hash]}"
    }
  }

  fingerprint {
    method => "SHA256"
    source => "raw_string_for_hash"
    target => "logstash_calculated_hash"
  }

  if [audit_chain][hash] and [logstash_calculated_hash] {
    if [audit_chain][hash] != [logstash_calculated_hash] {
      mutate {
        add_tag => ["ALERTE_FALSIFICATION_HASH"]
      }
    }
  }

  mutate {
    remove_field => ["logstash_calculated_hash", "raw_string_for_hash"]
  }
}