# Configuration de Logstash pour ingérer les données de sécurité et les envoyer à Elasticsearch
input {
  http {
    port => 5044
    codec => json
  }
}

# Filtrage pour vérifier la présence des champs "sequence_number" et "hash"
filter {
  if ![sequence_number] or ![hash] {
    mutate { add_tag => ["alerte_integrite_manquante"] }
  }
}

# Envoi des données à Elasticsearch et affichage dans la console pour le débogage
output {
  elasticsearch {
    hosts => "elasticsearch:9200"
    user => "logstash_internal"
    password => "${LOGSTASH_INTERNAL_PASSWORD}"
    index => "security-audit-%{+YYYY.MM.dd}"
    
    action => "create"
  }
  stdout { codec => rubydebug }
}