input {
  file {
    path => "/usr/share/logstash/audit-logs/*audit*.json"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb_audit"
    codec => "json"
    type => "es_audit"
  }
}
