output {
  elasticsearch {
    hosts                       => ["https://elasticsearch:9200"]
    user                        => "logstash_alerts_writer"
    password                    => "${LOGSTASH_ALERTS_PASSWORD}"
    index                       => "security-alerts"
    action                      => "create"
    ssl_enabled                 => true
    ssl_certificate_authorities => "/usr/share/logstash/config/certs/ca-chain.pem"
  }
}
