services:
  postgres_keycloak:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - auth-network
  pki:
    image: debian:bookworm-slim
    container_name: pki_authority
    env_file:
      - pki/pki.env
    volumes:
      - ./pki:/etc/pki/CA/config
      - pki_secrets:/etc/pki/CA
      - pki_public:/etc/pki/CA/certs
    command: tail -f /dev/null
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_FEATURES: web-authn
    ports:
      - "8080:8080"
    depends_on:
      - postgres_keycloak
      - pki
    networks:
      - auth-network
    volumes:
      - pki_public:/opt/keycloak/conf/truststores
networks:
  auth-network:
    driver: bridge

volumes:
  postgres_data:
  pki_secrets:
  pki_public: