services:
  postgres_keycloak:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - auth-network

  pki:
    image: debian:bookworm-slim
    container_name: pki_authority
    env_file:
      - pki/pki.env
    volumes:
      - ./pki:/etc/pki/CA/config
      - pki_secrets:/etc/pki/CA
      - pki_public:/etc/pki/CA/certs
    command: >
      bash -c "
      chmod +x /etc/pki/CA/config/pki_deploy.sh &&
      /etc/pki/CA/config/pki_deploy.sh &&
      tail -f /dev/null
      "
    networks:
      - auth-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    entrypoint: >
      /bin/bash -c "
      until [ -f /opt/keycloak/conf/truststores/root-ca.crt ]; do sleep 2; done &&
      rm -f /tmp/truststore.p12 &&
      keytool -import -alias root-ca -file /opt/keycloak/conf/truststores/root-ca.crt -keystore /tmp/truststore.p12 -storepass $${KEYCLOAK_TRUSTSTORE_PASSWORD} -noprompt &&
      keytool -import -alias signing-ca -file /opt/keycloak/conf/truststores/signing-ca1.crt -keystore /tmp/truststore.p12 -storepass $${KEYCLOAK_TRUSTSTORE_PASSWORD} -noprompt &&
      /opt/keycloak/bin/kc.sh start-dev --import-realm
      "
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_FEATURES: web-authn
      KC_HOSTNAME_STRICT: "false"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/truststores/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/truststores/server.key
      KC_HTTPS_TRUST_STORE_FILE: /tmp/truststore.p12
      KC_HTTPS_TRUST_STORE_PASSWORD: ${KEYCLOAK_TRUSTSTORE_PASSWORD}
      KC_HTTPS_CLIENT_AUTH: request
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres_keycloak
      - pki
    networks:
      - auth-network
    volumes:
      - pki_public:/opt/keycloak/conf/truststores
      - ./keycloak/import/realm-export.json:/opt/keycloak/data/import/realm.json
networks:
  auth-network:
    driver: bridge

volumes:
  postgres_data:
  pki_secrets:
  pki_public: